<?php
// lang.php
// 言語ごとのテキストを連想配列で管理

$lang_data = [
  'ja' => [
    'title' => '決済方法検索システム',
    'search' => '店舗検索',
    'register' => '店舗登録',
    'english' => 'English',
    'japanese' => '日本語',
    'search_result' => '検索結果',
    'no_results' => '条件に合う店舗は見つかりませんでした。',
    'return_search' => '検索画面に戻る',
    'shop_name' => '店舗名を入力',
    'area' => '地域を入力',
    'payment' => '決済方法を選択',
    'category' => '業種を選択',
    'search_button' => '検索',
    'payment_options' => ['credit' => 'クレジットカード', 'qr' => 'QRコード決済', 'emoney' => '電子マネー', 'cash' => '現金払い'],
    'category_options' => ['food' => '飲食', 'retail' => '小売', 'service' => 'サービス'],
    'subscribe_title' => 'お知らせを受け取る',
    'subscribe_desc' => '将来的なアップデートを希望する方は登録してください',
    'name' => 'お名前',
    'email' => 'メールアドレス',
    'subscribe_button' => '登録',
    'usage' => '使い方',
    'usage_desc' => '検索フォームに必要な条件を入力し、「検索」を押すと、条件に合う店舗情報の一覧が表示されます。',
    'notice' => '注意事項',
    'notice_desc' => '店舗情報は最新の情報を反映するよう努めていますが、訪問前に店舗に直接確認することをおすすめします。',
  ],
  'en' => [
    'title' => 'Payment Method Search System',
    'search' => 'Shop Search',
    'register' => 'Register Shop',
    'english' => 'English',
    'japanese' => 'Japanese',
    'search_result' => 'Search Results',
    'no_results' => 'No shops matched your criteria.',
    'return_search' => 'Return to Search',
    'shop_name' => 'Enter Shop Name',
    'area' => 'Enter Area',
    'payment' => 'Select Payment Method',
    'category' => 'Select Category',
    'search_button' => 'Search',
    'payment_options' => ['credit' => 'Credit Card', 'qr' => 'QR Code Payment', 'emoney' => 'Electronic Money', 'cash' => 'Cash'],
    'category_options' => ['food' => 'Food & Drink', 'retail' => 'Retail', 'service' => 'Service'],
    'subscribe_title' => 'Subscribe for Updates',
    'subscribe_desc' => 'Register here if you want future updates.',
    'name' => 'Name',
    'email' => 'Email',
    'subscribe_button' => 'Subscribe',
    'usage' => 'Usage',
    'usage_desc' => 'Fill in the search form and press "Search" to display shops matching your criteria.',
    'notice' => 'Notice',
    'notice_desc' => 'We try to keep shop information up to date, but please confirm directly with shops before visiting.',
  ],
];
